// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: upgrade_chirpy_red.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const updateChirpyRed = `-- name: UpdateChirpyRed :one
UPDATE users
SET
    is_chirpy_red = $1
WHERE
    id = $2
    RETURNING id, created_at, updated_at, email, hashed_password, is_chirpy_red
`

type UpdateChirpyRedParams struct {
	IsChirpyRed bool
	ID          uuid.UUID
}

func (q *Queries) UpdateChirpyRed(ctx context.Context, arg UpdateChirpyRedParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateChirpyRed, arg.IsChirpyRed, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
		&i.IsChirpyRed,
	)
	return i, err
}
